Traceback (most recent call last):
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from reaktoro import *

db = PhreeqcDatabase("phreeqc.dat")

solution = AqueousPhase(speciate("H O Na Cl C Ca Si"))
solution.set(ActivityModelPhreeqc(db))

gases = GaseousPhase("CO2(g) H2O(g)")
gases.set(ActivityModelPengRobinsonSoreideWhitson())

minerals = MineralPhases()

system = ChemicalSystem(db, solution, gases, minerals)

state = ChemicalState(system)
state.temperature(60.0, "celsius")
state.pressure(15.0, "atm")
state.set("H2O"    , 1.0, "kg")
state.set("Na+"    , 1.0, "mol")
state.set("Cl-"    , 1.0, "mol")
state.set("CO2"    , 0.7, "mol")
state.set("Calcite", 1.0, "g")
state.set("Quartz" , 1.0, "g")

equilibrate(state)

aprops = AqueousProps(state)

print(aprops)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mreaktoro[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      3[0m db[38;5;250m [39m[38;5;241m=[39m[38;5;250m [39m[38;5;21;01mPhreeqcDatabase[39;00m([38;5;124m"[39m[38;5;124mphreeqc.dat[39m[38;5;124m"[39m)
[1;32m      5[0m solution[38;5;250m [39m[38;5;241m=[39m[38;5;250m [39m[38;5;21;01mAqueousPhase[39;00m([38;5;21mspeciate[39m([38;5;124m"[39m[38;5;124mH O Na Cl C Ca Si[39m[38;5;124m"[39m))

File [0;32m~/miniconda3/envs/reaktoro-jupyter-book/lib/python3.11/site-packages/reaktoro/__init__.py:1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mreaktoro[39;00m[38;5;21;01m.[39;00m[38;5;21;01mreaktoro4py[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mreaktoro[39;00m[38;5;21;01m.[39;00m[38;5;21;01mextensions[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mautodiff[39;00m

[0;31mImportError[0m: libspdlog.so.1.11: cannot open shared object file: No such file or directory
ImportError: libspdlog.so.1.11: cannot open shared object file: No such file or directory

